"""Assemble eight ImageGen walking poses with genuine alpha into an advancing loop.
Requires Pillow and imageio-ffmpeg from requirements-animation.txt.
The source art is generated by ImageGen; this is video/frame assembly only.
"""
from pathlib import Path
from PIL import Image
import imageio_ffmpeg
import json

ROOT=Path(__file__).resolve().parents[1]
ASSETS=ROOT/'assets'
EXPORT=ROOT/'exports'
sheet=Image.open(ASSETS/'source'/'elly-pigeon-walk-spritesheet.png').convert('RGBA')
cw,ch=sheet.width//4,sheet.height//2
cells=[sheet.crop((c*cw,r*ch,(c+1)*cw,(r+1)*ch)) for r in range(2) for c in range(4)]
boxes=[cell.getchannel('A').point(lambda a:255 if a>32 else 0).getbbox() for cell in cells]
if any(box is None for box in boxes):raise ValueError('A walking pose is empty')
box=(min(b[0] for b in boxes),min(b[1] for b in boxes),max(b[2] for b in boxes),max(b[3] for b in boxes))
factor=min(380/(box[2]-box[0]),380/(box[3]-box[1]),1)
size=(round((box[2]-box[0])*factor),round((box[3]-box[1])*factor))
# Downsample only. Never enlarge the generated glyphs with nearest-neighbor.
poses=[cell.crop(box).resize(size,Image.Resampling.LANCZOS) for cell in cells]
width,height=880,440
frames=[]
for i in range(128):
    # An 0.8-second gait cycle; a 6.4-second traversal, wrapping offscreen.
    pose=poses[(i//2)%8]
    phase=(i/128+0.40)%1
    x=round(phase*(width+size[0])-size[0])
    canvas=Image.new('RGBA',(width,height),(0,0,0,0))
    canvas.alpha_composite(pose,(x,height-size[1]-26))
    frames.append(canvas)
webp=ASSETS/'elly-pigeon-walk.webp'
# The app translates this compact eight-pose lossless loop with CSS; exports
# include the complete traversal. This avoids downloading 128 large poses.
frames[0].save(EXPORT/'elly-ring-pigeon-walk.webp',save_all=True,append_images=frames[1:],duration=50,loop=0,lossless=True,quality=100,method=1,exact=True)
poses[0].save(webp,save_all=True,append_images=poses[1:],duration=100,loop=0,lossless=True,quality=100,method=1,exact=True)
poses[0].save(ASSETS/'elly-pigeon-poster.png')
# GIF is a separate compatibility export. Reserve palette entry 255 for alpha.
palette_board=Image.new('RGB',(cw*4,ch*2),(240,242,238))
for i,cell in enumerate(cells):
    flat=Image.new('RGBA',cell.size,(240,242,238,255));flat.alpha_composite(cell)
    palette_board.paste(flat.convert('RGB'),((i%4)*cw,(i//4)*ch))
palette=palette_board.quantize(colors=255,method=Image.Quantize.MEDIANCUT)
pal=palette.getpalette();pal[765:768]=[0,0,0];palette.putpalette(pal)
gif_frames=[]
for frame in frames[::2]:
    flat=Image.new('RGBA',frame.size,(240,242,238,255));flat.alpha_composite(frame)
    indexed=flat.convert('RGB').quantize(palette=palette,dither=Image.Dither.NONE)
    alpha=frame.getchannel('A').point(lambda a:255 if a<128 else 0)
    indexed.paste(255,(0,0),alpha)
    indexed.info['transparency']=255
    gif_frames.append(indexed)
gif=ASSETS/'elly-pigeon.gif'
gif_frames[0].save(gif,save_all=True,append_images=gif_frames[1:],duration=100,loop=0,transparency=255,disposal=2,optimize=False)
(EXPORT/'elly-ring-pigeon-walk.gif').write_bytes(gif.read_bytes())
video=EXPORT/'elly-ring-pigeon-walk.mp4'
writer=imageio_ffmpeg.write_frames(str(video),(width,height),fps=20,macro_block_size=1,codec='libx264',pix_fmt_in='rgb24',pix_fmt_out='yuv420p',quality=9,output_params=['-movflags','+faststart','-metadata',"title=Elly's Ring - pixel pigeon walking"])
writer.send(None)
try:
    for _ in range(2):
        for frame in frames:
            flat=Image.new('RGBA',frame.size,(240,242,238,255));flat.alpha_composite(frame)
            writer.send(flat.convert('RGB').tobytes())
finally:writer.close()
metadata={'size':[width,height],'background':'transparent WebP and GIF; app background in H.264 MP4','gait_seconds':0.8,'loop_seconds':6.4,'video_seconds':12.8,'frames':128,'fps':20,'webp':'lossless','sprite_pixels':list(size),'source':'assets/source/elly-pigeon-walk-spritesheet.png','generation':'Built-in ImageGen, eight walking poses'}
(EXPORT/'animation-walk.json').write_text(json.dumps(metadata,indent=2),encoding='utf-8')
print(json.dumps(metadata))
print('WebP:',webp.stat().st_size,'GIF:',gif.stat().st_size,'MP4:',video.stat().st_size)


